# Generated by Django 3.2.7 on 2021-11-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('Civil', 'Civil Engineering'), ('AI&DS', 'Artifical Inteligence')], max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('f_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=200)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('prn_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('paswrd', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('f_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('bday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('on_date', models.DateField()),
                ('desc', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subject')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.teacher'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now=True)),
                ('attendence', models.BooleanField(default=True)),
                ('remarks', models.TextField(max_length=50)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.students')),
            ],
        ),
    ]
